### ISSUE TITLE
BLP revise job submission issue wording

### ISSUE THREAD

**Issue by ShiqiYang2022** [ShiqiYang2022/template#15]
Thanks chiefs in advance helping me revise the issue wording ❤️ .

**Comment by ShiqiYang2022** [comment]
Follows https://github.com/gslab-econ/blp-instruments/issues/189#issue-1943539862 https://github.com/gslab-econ/blp-instruments/issues/168#issuecomment-1756471497. This issue aims to revise job submission structure to get the computing setup for blp-instruments better organized so that it's easier to work with in the future revise tasks.

The main tasks of this issue is listed below by priority:

- [ ] Determine the resources that need to be used for each job. This includes trials and testing the pipeline
- [ ] Revise job submission structure to (1) allocate least computing resource possible on each job; (2) reducing the total amount of job in submission without get beyond of sherlock capacity
- [ ] Revise the code pipeline to enable only one user to run the full run.
- [ ] Conduct the full run of the pipeline to confirm output stability.
- [ ] (If possible) Reach out to research computing teams and evaluate how to make compute setup more efficient.

@ShiqiYang2022 will take the lead of this task, while @snairdesai @jc-cisneros give input as helping him familiarize with the pipeline, and testing the submission together.

cc: JMS MG NB.

**Comment by ShiqiYang2022** [comment]
For the title I would like to use "Revise job submission structure".

**Comment by ShiqiYang2022** [comment]
@jc-cisneros @snairdesai it would be sweet if you could give me some suggestions on this, and I plan to open this issue at 9:30 PM if you have time to give it a quick shot, or if not, I will open this by the time Jesse wake up as his breakfast 🍞 🍳 🥓 .

**Comment by jc-cisneros** [comment]
Follows https://github.com/gslab-econ/blp-instruments/issues/189#issue-1943539862 https://github.com/gslab-econ/blp-instruments/issues/168#issuecomment-1756471497. The goal of this issue is to improve the efficiency and readability of the `analysis_cluster` module.

The main tasks of this issue are listed below by priority:

- [ ] Determine the optimal resources that need to be used for each job. To do this, we can begin testing the runtime of each combination.
- [ ] Revise job submission to reduce the total number of jobs submitted (substantially).
- [ ] Revise the code pipeline to enable only one user to run the full run. This is currently feasible through the partitions but would probably take over a week in practice (and maybe even longer).
- [ ] Reach out to Sherlock support and discuss how to make the cluster pipeline more efficient. Note that @jc-cisneros and @snairdesai have done this before so we can follow up on this thread.

@ShiqiYang2022 will take the lead on this task, while @snairdesai @jc-cisneros will provide input to help him familiarize himself with the pipeline, and test the submissions together.

cc: JMS MG NB.

**Comment by snairdesai** [comment]
^@ShiqiYang2022 I was with JC when he wrote so agree the above looks perfect. You may add links to prior issues (161, 168, 189) as well if needed. I also recall NB mentioned something about optimizing the residualizing code in MATLAB so can add that too.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros @snairdesai thanks guys! Opening the issue now.

**Comment by ShiqiYang2022** [comment]
A big 💣 is on the way
