### ISSUE TITLE
Shrish Tasks description

### ISSUE THREAD

**Issue by ShiqiYang2022** [ShiqiYang2022/template#16]

**Comment by ShiqiYang2022** [comment]
## Preparation shell functions used in new template

This issue is opened for drafting a list of functionality that might be used in our future shell-based template. To do this, @snairdesai @jc-cisneros and I will help @ Shirish get familiar with:

- [ ] [gentzkow template](https://github.com/gentzkow/template)
- [ ] [`gslab_make`](https://github.com/gslab-econ/gslab_make) library

while @ Arjun will help(Thanks for helps here!) Shirish get familiar with

- [ ] His [existing template](https://github.com/arjunsrini/TunaTemplate) constructed based on shell functions, and the corresponding [`"shell make"`](https://github.com/arjunsrini/shmake). 

After getting fully familiar with all the functionalities listed above, @ Shirish is requested to compile lists of:

- [ ] Functionalities that is currently living in our template but not in shell template 
- [ ] Functionalities that is currently living in shell template but not our template. 

Please reach out to us at anytime if you have questions, thanks!

**Comment by ShiqiYang2022** [comment]
Assign Shrish and we three.

**Comment by jc-cisneros** [comment]
## Compile a list of functionalities of current template structures

The goal of this issue is to draft a list of functionalities (e.g., moving files across modules or logging runs) that template/gslab_make and Arjun's solution currently have. To do this, @snairdesai @jc-cisneros and I will help @ Shrish get familiar with:

- [ ] [gentzkow template](https://github.com/gentzkow/template)
- [ ] [`gslab_make`](https://github.com/gslab-econ/gslab_make) library

while @ Arjun will help (thanks for helping here!) Shrish with

- [ ] His [existing template](https://github.com/arjunsrini/TunaTemplate) constructed based on shell functions, and the corresponding [`"shell make"`](https://github.com/arjunsrini/shmake). 

The deliverable is a list of functionalities that we have in template/gslab_make but not in Arjun's shell template and viceversa. @ Shrish, please reach out to us at any time if you have questions, thanks!

**Comment by jc-cisneros** [comment]
@ShiqiYang2022 my suggestions above. @snairdesai let us know what you think.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros Love you as always 💌 Thanks!

**Comment by ShiqiYang2022** [comment]
What do you guys think open the issue in the early tmr morning, say at 8 AM?

**Comment by ShiqiYang2022** [comment]
Perhaps sending email at night is a bit strange.
